### ISSUE TITLE
Remove welcome page

### ISSUE THREAD

**Issue by sneumann** [ipb-halle/GoldenMutagenesisWeb#30]
Hi, I'd like to suggest to remove the welcome page. This will save power-users 
a click and directly get them to the sequence. Instead, the citation
could be added to the bottom of the menu, and/or a separate "About" page. 
Yours, Steffen

**Comment by culpinnis** [comment]
The users have to select the desired task anyway, there is no useful preset (like e.g. Single Point Mutagenesis).
