### ISSUE TITLE
Container configuration invalid

### ISSUE THREAD

**Issue by culpinnis** [ipb-halle/GoldenMutagenesisWeb#31]
Hey together, 

It looks like something was changed in previous releases of the Rocker Shiny container. While the GoldenMutagenesis application is sane (the last update was on my last working day introducing newly available vectors), the container crashes on startup. This is not an issue of the web application itself - I guess something needs to be configured in the Dockerfile or in Kubernetes. I cloud not acquire enough time to test the container outside of IPBs Kubernetes yet. 
Pascal and Anja would be very happy to use the newly implemented vectors ;) 

The container complains about 

```bash 
s6-mkdir: warning: unable to mkdir /var/run/s6: Permission denied
```
Maybe one of you can fix the bug easily. 

Best wishes
Chris

**Comment by sneumann** [comment]
Hi, is that affecting the running version, or preventing update to a newer GoldenMutagenesis ? Yours, Steffen

**Comment by sneumann** [comment]
Sounds a bit like https://github.com/janeczku/docker-alpine-kubernetes/issues/7#issuecomment-202985555

**Comment by culpinnis** [comment]
The new version was already built by our CI pipeline. I tried to deploy it in Kubernetes, but because of the crashing container it still delivers the old containers. But I guess if those containers die for any reason, the application will not be available anymore.

**Comment by culpinnis** [comment]
<img width="1454" alt="Bildschirmfoto 2020-09-24 um 18 10 33" src="https://user-images.githubusercontent.com/2099798/94171196-4506ad80-fe91-11ea-9e6f-a0afe2ecf5e0.png">
We collected over 6400 restarts at the moment 😅...

**Comment by sneumann** [comment]
Temporary fix is to pin an older rockr version

**Comment by culpinnis** [comment]
> Sounds a bit like [janeczku/docker-alpine-kubernetes#7 (comment)](https://github.com/janeczku/docker-alpine-kubernetes/issues/7#issuecomment-202985555)

Yes maybe it's enough the change the CMD line to run the shiny server directly by the shiny user instead of setting the user in the config file (which was deprecated if I remember correctly - at least there was a warning about starting as root user...)

**Comment by culpinnis** [comment]
I guess other application like MetFamily could be affected when they are rebuilt, too

**Comment by sneumann** [comment]
Hi, I can confirm the issue without kubernetes already with  `docker run -p 3838:3838 sneumann/goldenmutagenesisweb`
Also, see discussion in https://github.com/rocker-org/shiny/issues/79 .
In Short: the shiny image now uses `supervisord` to start:
https://github.com/rocker-org/rocker-versioned2/blob/master/dockerfiles/Dockerfile_shiny_4.0.0#L17
which can't run as `USER shiny`. 
One solution is to 1) configure shiny to run as `shiny` and 2) to override `CMD` with the old behaviour. 
Yours, Steffen

**Comment by sneumann** [comment]
We now have a running `
R version 4.0.2 (2020-06-22) goldenmutagenesisweb-deployment-6f5cf5cb79-98hlg
` 
Yours, Steffen

**Comment by culpinnis** [comment]
I updated the app version, it should show the correct date now.
