### ISSUE TITLE
Sequence input checks on page one

### ISSUE THREAD

**Issue by sneumann** [ipb-halle/GoldenMutagenesisWeb#4]
Hi, the checks on the input sequence 
(length mod 3 == 0, Methionine and stop codon) 
should already be on page one, before proceeding 
to the configuration page.

**Comment by culpinnis** [comment]
Related to #6

**Comment by culpinnis** [comment]
The users wish to only have a warning for missing start or stop codons. 
This needs to be also addressed in ipb-halle/GoldenMutagenesis

**Comment by culpinnis** [comment]
Implemented without the feature request, will be a new issue.
